"""Substance table

Revision ID: 262464d761c0
Revises: 8ac12ceee80e
Create Date: 2020-04-14 10:08:12.185636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262464d761c0'
down_revision = '8ac12ceee80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('substance', sa.Column('title', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_substance_title'), 'substance', ['title'], unique=True)
    op.drop_index('ix_substance_substance', table_name='substance')
    op.drop_column('substance', 'substance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('substance', sa.Column('substance', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_substance_substance', 'substance', ['substance'], unique=1)
    op.drop_index(op.f('ix_substance_title'), table_name='substance')
    op.drop_column('substance', 'title')
    # ### end Alembic commands ###
