"""substances table

Revision ID: 5a9f2383ca96
Revises: 7200bb088c32
Create Date: 2020-04-13 10:57:40.284818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9f2383ca96'
down_revision = '7200bb088c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('substance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('substance', sa.String(length=64), nullable=True),
    sa.Column('fiz', sa.String(length=64), nullable=True),
    sa.Column('fiz2', sa.String(length=64), nullable=True),
    sa.Column('put', sa.String(length=64), nullable=True),
    sa.Column('put2', sa.String(length=64), nullable=True),
    sa.Column('put3', sa.String(length=64), nullable=True),
    sa.Column('put4', sa.String(length=64), nullable=True),
    sa.Column('kli', sa.String(length=64), nullable=True),
    sa.Column('kli2', sa.String(length=64), nullable=True),
    sa.Column('kli3', sa.String(length=64), nullable=True),
    sa.Column('kli4', sa.String(length=64), nullable=True),
    sa.Column('kli5', sa.String(length=64), nullable=True),
    sa.Column('kli6', sa.String(length=64), nullable=True),
    sa.Column('kli7', sa.String(length=64), nullable=True),
    sa.Column('kli8', sa.String(length=64), nullable=True),
    sa.Column('kli9', sa.String(length=64), nullable=True),
    sa.Column('kli10', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_substance_substance'), 'substance', ['substance'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_substance_substance'), table_name='substance')
    op.drop_table('substance')
    # ### end Alembic commands ###
