"""new fields in user model

Revision ID: 8ac12ceee80e
Revises: 5a9f2383ca96
Create Date: 2020-04-13 11:35:53.583382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac12ceee80e'
down_revision = '5a9f2383ca96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('notes', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'notes')
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
